aboxes_inconsistent = ['a:A, a:E',
'a:(A&E)',
'a:(E&A)',
'a:A, a:(E&B)',
'a:A, a:(B&E)',
'a:E, a:(A&B)',
'a:E, a:(B&A)',
'a:A, (b,a):r, b:/Ar.E',
'a:E, (b,a):r, b:/Ar.A',
'a:((A&E)&B)',
'a:((E&A)&B)',
'a:(B&(A&E))',
'a:(B&(E&A))',
'a:(A&(B&E))',
'a:(A&(E&B))',
'a:((B&E)&A)',
'a:((E&B)&A)',
'a:(E&(B&A))',
'a:(E&(A&B))',
'a:((B&A)&E)',
'a:((A&B)&E)',
'a:A, a:(E&(B&C))',
'a:A, a:((B&C)&E)',
'a:A, a:(B&(E&C))',
'a:A, a:(B&(C&E))',
'a:A, a:((E&C)&B)',
'a:A, a:((C&E)&B)',
'a:E, a:(A&(B&C))',
'a:E, a:((B&C)&A)',
'a:E, a:(B&(A&C))',
'a:E, a:(B&(C&A))',
'a:E, a:((A&C)&B)',
'a:E, a:((C&A)&B)',
'a:(A&C), a:(E&B)',
'a:(C&A), a:(E&B)',
'a:(A&C), a:(B&E)',
'a:(C&A), a:(B&E)',
'a:A, (c,b):r, (b,a):s, c:/Ar./As.E',
'a:E, (c,b):r, (b,a):s, c:/Ar./As.A',
'b:/Er.A, b:/Ar.E',
'b:/Er.E, b:/Ar.A',
'b:/Ar.A, (b,a):r, b:/Ar.E',
'(c,a):s, c:/As.A, (b,a):r, b:/Ar.E',
'a:A, (b,a):r, b:(B&/Ar.E)',
'a:A, (b,a):r, b:((/Ar.E)&B)',
'a:E, (b,a):r, b:(B&/Ar.A)',
'a:E, (b,a):r, b:((/Ar.A)&B)',
'a:A, (b,a):r, b:/Ar.(E&B)',
'a:A, (b,a):r, b:/Ar.(B&E)',
'a:E, (b,a):r, b:/Ar.(A&B)',
'a:E, (b,a):r, b:/Ar.(B&A)',
'a:(A&B), (b,a):r, b:/Ar.E',
'a:(B&A), (b,a):r, b:/Ar.E',
'a:(E&B), (b,a):r, b:/Ar.A',
'a:(B&E), (b,a):r, b:/Ar.A',
'a:(((A&E)&B)&C)',
'a:(C&((A&E)&B))',
'a:(((E&A)&B)&C)',
'a:(C&((E&A)&B))',
'a:((B&(A&E))&C)',
'a:(C&(B&(A&E)))',
'a:((B&(E&A))&C)',
'a:(C&(B&(E&A)))',
'a:(A&(B&(C&E)))',
'a:(A&(B&(E&C)))',
'a:(A&((C&E)&B))',
'a:(A&((E&C)&B))',
'a:((B&(C&E))&A)',
'a:((B&(E&C))&A)',
'a:(((C&E)&B)&A)',
'a:(((E&C)&B)&A)',
'a:(E&(B&(C&A)))',
'a:(E&(B&(A&C)))',
'a:(E&((C&A)&B))',
'a:(E&((A&C)&B))',
'a:((B&(C&A))&E)',
'a:((B&(A&C))&E)',
'a:(((C&A)&B)&E)',
'a:(((A&C)&B)&E)',
'a:(A&(E&(B&C)))',
'a:(A&((B&C)&E))',
'a:(E&(A&(B&C)))',
'a:(E&((B&C)&A))',
'a:((E&(B&C))&A)',
'a:(((B&C)&E)&A)',
'a:((A&(B&C))&E)',
'a:(((B&C)&A)&E)',
'a:A, a:(E&(B&(C&D)))',
'a:A, a:((B&(C&D))&E)',
'a:A, a:(E&((C&D)&B))',
'a:A, a:(((C&D)&B)&E)',
'a:A, a:(B&(E&(C&D)))',
'a:A, a:(B&((C&D)&E))',
'a:A, a:((E&(C&D))&B)',
'a:A, a:(((C&D)&E)&B)',
'a:A, a:(B&(C&(E&D)))',
'a:A, a:(B&(C&(D&E)))',
'a:A, a:((C&(E&D))&B)',
'a:A, a:((C&(D&E))&B)',
'a:A, a:(B&((E&D)&C))',
'a:A, a:(B&((D&E)&C))',
'a:A, a:(((E&D)&C)&B)',
'a:A, a:(((D&E)&C)&B)',
'a:E, a:(A&(B&(C&D)))',
'a:E, a:((B&(C&D))&A)',
'a:E, a:(A&((C&D)&B))',
'a:E, a:(((C&D)&B)&A)',
'a:E, a:(B&(A&(C&D)))',
'a:E, a:(B&((C&D)&A))',
'a:E, a:((A&(C&D))&B)',
'a:E, a:(((C&D)&A)&B)',
'a:E, a:(B&(C&(A&D)))',
'a:E, a:(B&(C&(D&A)))',
'a:E, a:((C&(A&D))&B)',
'a:E, a:((C&(D&A))&B)',
'a:E, a:(B&((A&D)&C))',
'a:E, a:(B&((D&A)&C))',
'a:E, a:(((A&D)&C)&B)',
'a:E, a:(((D&A)&C)&B)',
'a:(A&B), a:(E&(C&D))',
'a:(A&B), a:((C&D)&E)',
'a:(A&B), a:((E&D)&C)',
'a:(A&B), a:((D&E)&C)',
'a:(A&B), a:(C&(E&D))',
'a:(A&B), a:(C&(D&E))',
'a:(B&A), a:(E&(C&D))',
'a:(B&A), a:((C&D)&E)',
'a:(B&A), a:((E&D)&C)',
'a:(B&A), a:((D&E)&C)',
'a:(B&A), a:(C&(E&D))',
'a:(B&A), a:(C&(D&E))',
'a:(E&B), a:(A&(C&D))',
'a:(E&B), a:((C&D)&A)',
'a:(E&B), a:((A&D)&C)',
'a:(E&B), a:((D&A)&C)',
'a:(E&B), a:(C&(A&D))',
'a:(E&B), a:(C&(D&A))',
'a:(B&E), a:(A&(C&D))',
'a:(B&E), a:((C&D)&A)',
'a:(B&E), a:((A&D)&C)',
'a:(B&E), a:((D&A)&C)',
'a:(B&E), a:(C&(A&D))',
'a:(B&E), a:(C&(D&A))',
'a:A, (d,c):r, (c,b):s, (b,a):t, d:/Ar./As./At.E',
'a:E, (d,c):r, (c,b):s, (b,a):t, d:/Ar./As./At.A',
'(b,c):r, c:/Es.A, b:/Ar/As.E',
'(b,c):r, c:/Es.E, b:/Ar/As.A',
'b:/Ar./Es.A, (b,c):r, c:/As.E',
'b:/Ar./Es.E, (b,c):r, c:/As.A',
'(b,c):r, (c,a):s, c:/As.A, b:/Ar./As.E',
'(b,c):r, (c,a):s, c:/As.E, b:/Ar./As.A',
'a:A, (b,a):r, b:/Ar.((E&B)&C)',
'a:A, (b,a):r, b:/Ar.((B&E)&C)',
'a:A, (b,a):r, b:/Ar.(C&(E&B))',
'a:A, (b,a):r, b:/Ar.(C&(B&E))',
'a:E, (b,a):r, b:/Ar.((A&B)&C)',
'a:E, (b,a):r, b:/Ar.((B&A)&C)',
'a:E, (b,a):r, b:/Ar.(C&(A&B))',
'a:E, (b,a):r, b:/Ar.(C&(B&A))',
'a:A, (b,a):r, b:(C&/Ar.(E&B))',
'a:A, (b,a):r, b:((/Ar.(E&B))&C)',
'a:A, (b,a):r, b:(C&/Ar.(B&E))',
'a:A, (b,a):r, b:((/Ar.(B&E))&C)',
'a:E, (b,a):r, b:(C&/Ar.(A&B))',
'a:E, (b,a):r, b:((/Ar.(A&B))&C)',
'a:E, (b,a):r, b:(C&/Ar.(B&A))',
'a:E, (b,a):r, b:((/Ar.(B&A))&C)',
'a:A, (b,a):r, b:(B&(C&/Ar.E))',
'a:A, (b,a):r, b:(B&((/Ar.E)&C))',
'a:A, (b,a):r, b:((C&/Ar.E)&B)',
'a:A, (b,a):r, b:(((/Ar.E)&C)&B)',
'a:E, (b,a):r, b:(B&(C&/Ar.A))',
'a:E, (b,a):r, b:(B&((/Ar.A)&C))',
'a:E, (b,a):r, b:((C&/Ar.A)&B)',
'a:E, (b,a):r, b:(((/Ar.A)&C)&B)',
'a:((A&B)&C), (b,a):r, b:/Ar.E',
'a:(C&(A&B)), (b,a):r, b:/Ar.E',
'a:(A&(B&C)), (b,a):r, b:/Ar.E',
'a:((B&C)&A), (b,a):r, b:/Ar.E',
'a:((E&B)&C), (b,a):r, b:/Ar.A',
'a:(C&(E&B)), (b,a):r, b:/Ar.A',
'a:(E&(B&C)), (b,a):r, b:/Ar.A',
'a:((B&C)&E), (b,a):r, b:/Ar.A',
'a:(A&B), (b,a):r, b:/Ar.(E&B)',
'a:(A&B), (b,a):r, b:/Ar.(B&E)',
'a:(B&A), (b,a):r, b:/Ar.(E&B)',
'a:(B&A), (b,a):r, b:/Ar.(B&E)',
'a:(E&B), (b,a):r, b:/Ar.(A&B)',
'a:(E&B), (b,a):r, b:/Ar.(B&A)',
'a:(B&E), (b,a):r, b:/Ar.(A&B)',
'a:(B&E), (b,a):r, b:/Ar.(B&A)',
'a:(A&B), (b,a):r, b:(C&/Ar.E)',
'a:(A&B), (b,a):r, b:((/Ar.E)&C)',
'a:(B&A), (b,a):r, b:(C&/Ar.E)',
'a:(B&A), (b,a):r, b:((/Ar.E)&C)',
'a:(E&B), (b,a):r, b:(C&/Ar.A)',
'a:(E&B), (b,a):r, b:((/Ar.A)&C)',
'a:(B&E), (b,a):r, b:(C&/Ar.A)',
'a:(B&E), (b,a):r, b:((/Ar.A)&C)',
'a:A, (c,b):r, (b,a):s, c:(B&/Ar./As.E)',
'a:A, (c,b):r, (b,a):s, c:((/Ar./As.E)&B)',
'a:E, (c,b):r, (b,a):s, c:(B&/Ar./As.A)',
'a:E, (c,b):r, (b,a):s, c:((/Ar./As.A)&B)',
'a:A, (c,b):r, (b,a):s, c:(/Ar./As.(B&E))',
'a:A, (c,b):r, (b,a):s, c:(/Ar./As.(E&B))',
'a:E, (c,b):r, (b,a):s, c:(/Ar./As.(B&A))',
'a:E, (c,b):r, (b,a):s, c:(/Ar./As.(A&B))',
'a:(A&B), (c,b):r, (b,a):s, c:(/Ar./As.E)',
'a:(B&A), (c,b):r, (b,a):s, c:(/Ar./As.E)',
'a:(E&B), (c,b):r, (b,a):s, c:(/Ar./As.A)',
'a:(B&E), (c,b):r, (b,a):s, c:(/Ar./As.A)',
'a:A, (c,b):r, (b,a):s, c:(/Ar.(B&/As.E))',
'a:A, (c,b):r, (b,a):s, c:/Ar.((/As.E)&B)',
'a:E, (c,b):r, (b,a):s, c:(/Ar.(B&/As.A))',
'a:E, (c,b):r, (b,a):s, c:/Ar.((/As.A)&B)',
'b:(/Er.A&/Ar.E)',
'b:(/Er.E&/Ar.A)',
'b:(/Ar.E&/Er.A)',
'b:(/Ar.A&/Er.E)',
'b:/Er.E, b:/Ar.(A&B)',
'b:/Er.E, b:/Ar.(B&A)',
'b:/Er.(E&B), b:/Ar.A',
'b:/Er.(B&E), b:/Ar.A',
'b:/Er.A, b:/Ar.(E&B)',
'b:/Er.A, b:/Ar.(B&E)',
'b:/Er.(A&B), b:/Ar.E',
'b:/Er.(B&A), b:/Ar.E',
'b:/Er.A, b:(B&/Ar.E)',
'b:/Er.A, b:((/Ar.E)&B)',
'b:/Er.E, b:(B&/Ar.A)',
'b:/Er.E, b:((/Ar.A)&B)',
'b:(B&/Er.A), b:/Ar.E',
'b:((/Er.A)&B), b:/Ar.E',
'b:(B&/Er.E), b:/Ar.A',
'b:((/Er.E)&B), b:/Ar.A']
